### ISSUE TITLE
能不能加入utls支持？

### ISSUE THREAD

**Issue by maskedeken** [JimmyHuang454/sing-box#1]

**Comment by JimmyHuang454** [comment]
可以加入utls，只要确保random是正确生成的即可，文档没有做这方面的规定，你可以选择加或者不加，不影响正常使用，全凭个人喜好。

首先我觉得，Client Hello的特征一般都是在套件上，比如说：Cipher Suites 和 Signature algorithm，这些都可以在代码上设置优先级，甚至singbox本身就可以让用户自定义 Cipher Suites。

目前最大的缺陷应该是 go和rust的tls都不加入padding，也就是要求Client Hello 长度必须大于512字节，这是RFC明确规定的。
